### ISSUE TITLE
Update Process documentation

### ISSUE THREAD

**Issue by fklemme** [bird-house/hummingbird#5]
As the catalog of services has changed recently, the documentation could use some update/rework.
See: http://birdhouse-hummingbird.readthedocs.org/en/latest/processes.html

**Comment by cehbrecht** [comment]
This is an ongoing task ... but we have now the nicely rendered process descriptions using the pywps Sphinx extension:

https://birdhouse-hummingbird.readthedocs.io/en/latest/processes.html

Detailed information for the processes is referenced by metadata links.
